services:
  - type: web
    name: my-nextjs-app
    env: node
    buildCommand: npm install -D tailwindcss@3.3.0 postcss@8.4.24 autoprefixer@10.4.14 && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_N8N_WEBHOOK_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 